#!/usr/bin/env python3
"""Generate a generic digest-bound candidate lock from a publish summary."""

from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from collections.abc import Callable
from pathlib import Path
from typing import Any

from profile_resolver import (
    find_stream,
    load_matrix,
    load_profile,
    resolve_profile,
    validate_candidate_id,
)


ROOT = Path(__file__).resolve().parents[1]
SUMMARY_VALIDATOR_PATH = ROOT / "scripts" / "validate-publish-summary.py"


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def reject_duplicate_keys(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON object key: {key!r}")
        result[key] = value
    return result


def load_json(path: Path) -> Any:
    with path.open(encoding="utf-8") as file_obj:
        return json.load(file_obj, object_pairs_hook=reject_duplicate_keys)


def load_summary_validator() -> Callable[..., list[str]]:
    spec = importlib.util.spec_from_file_location(
        "_validate_publish_summary",
        SUMMARY_VALIDATOR_PATH,
    )
    if spec is None or spec.loader is None:
        raise RuntimeError(f"could not load summary validator: {SUMMARY_VALIDATOR_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.validate_publish_summary


VALIDATE_PUBLISH_SUMMARY = load_summary_validator()


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Render a generic Kolla-Ansible candidate lock from publish output."
    )
    parser.add_argument("--publish-summary", required=True, type=Path)
    parser.add_argument("--stream", required=True, help="Build stream ID")
    parser.add_argument("--profile", required=True)
    parser.add_argument("--candidate-id", required=True)
    parser.add_argument("--output", type=Path, help="Write YAML lock here instead of stdout")
    return parser.parse_args()


def exact_mapping(actual: Any, expected: dict[str, Any]) -> bool:
    if not isinstance(actual, dict) or set(actual) != set(expected):
        return False
    return all(
        type(actual[key]) is type(expected_value) and actual[key] == expected_value
        for key, expected_value in expected.items()
    )


def render_lock(
    matrix: dict[str, Any],
    profile: dict[str, Any],
    stream: dict[str, Any],
    summary: dict[str, Any],
    candidate_id: str,
) -> str:
    candidate_id = validate_candidate_id(candidate_id)
    if profile.get("name") != "deployment":
        raise ValueError("candidate lock requires profile 'deployment'")
    if not isinstance(summary, dict):
        raise ValueError("publish summary must be an object")
    if summary.get("candidate_id") != candidate_id:
        raise ValueError(
            "publish summary candidate ID does not match expected candidate ID"
        )

    expected_scope = {
        "profile": "deployment",
        "image": "all",
        "image_count": len(profile["images"]),
    }
    if not exact_mapping(summary.get("scope"), expected_scope):
        raise ValueError(
            "candidate lock requires exact deployment/all scope "
            f"{expected_scope!r}, got {summary.get('scope')!r}"
        )

    errors = VALIDATE_PUBLISH_SUMMARY(
        matrix,
        profile,
        stream,
        summary,
        False,
        None,
        candidate_id,
    )
    if errors:
        details = "\n".join(f"- {error}" for error in errors)
        raise ValueError(f"publish summary validation failed:\n{details}")

    images = {image["image"]: image for image in summary["images"]}
    lines = [
        "# Generated by scripts/generate-lock.py from a complete publish summary.",
        "# Root-level *_image_full values use deploy tags compatible with Kolla-Ansible.",
        "# _kolla_candidate_lock binds those tags to immutable manifest digests.",
        "_kolla_candidate_lock:",
        "  schema_version: 1",
        f"  stream: {yaml_string(stream['id'])}",
        "  scope:",
        '    profile: "deployment"',
        '    image: "all"',
        f"    image_count: {expected_scope['image_count']}",
        "  images:",
    ]
    assignment_lines: list[str] = []
    emitted_variables: set[str] = set()

    for profile_image in profile["images"]:
        image_summary = images[profile_image["name"]]
        deploy_ref = image_summary["deploy_ref"]
        manifest_digest = image_summary["manifest_digest"]
        repository, _deploy_tag = deploy_ref.rsplit(":", 1)
        immutable_ref = f"{repository}@{manifest_digest}"
        variables = profile_image["kolla_ansible_variables"]

        lines.extend(
            (
                f"    {yaml_string(profile_image['name'])}:",
                f"      deploy_ref: {yaml_string(deploy_ref)}",
                f"      manifest_digest: {yaml_string(manifest_digest)}",
                f"      immutable_ref: {yaml_string(immutable_ref)}",
                "      kolla_ansible_variables:",
            )
        )
        for variable in variables:
            if variable in emitted_variables:
                raise ValueError(
                    f"resolved profile contains duplicate variable: {variable}"
                )
            emitted_variables.add(variable)
            lines.append(f"        - {yaml_string(variable)}")
            assignment_lines.append(f"{variable}: {yaml_string(deploy_ref)}")

    lines.extend(assignment_lines)
    return "\n".join(lines) + "\n"


def main() -> int:
    args = parse_args()

    try:
        matrix = load_matrix()
        stream = find_stream(matrix, args.stream)
        profile = resolve_profile(load_profile(args.profile), stream)
        summary = load_json(args.publish_summary)
        lock_yaml = render_lock(
            matrix,
            profile,
            stream,
            summary,
            args.candidate_id,
        )
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(str(exc), file=sys.stderr)
        return 2

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(lock_yaml, encoding="utf-8")
    else:
        print(lock_yaml, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
